### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by kmahyyg** [kmahyyg/ssrr_py_sub#1]
To-do list:
- [x] | 1. Correct incorrect padding error while decoding base64
- [x] | 2. Decode parameters 
- [x] | 3. Find the best server by ping rtt.
- [x] | 4. From url to JSON config
